name: CI

on: [push]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint PHP files
        run: find . -name "*.php" -print0 | xargs -0 -n1 -P3 php --syntax-check

      - name: Install SASS
        run: sudo npm install -g sass

      - name: Compile SASS
        run: sass --style=compressed csb/csb-themes/default/sass/style.scss:csb/csb-themes/default/style.css

      - name: Copy files to the build artifact folder
        # Exclude the .git folder from the build artifact
        run: rsync -av . /tmp/build --exclude .git

      - name: Archive build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: csb-build
          path: /tmp/build
